name: Deploy JaK to Github Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        working-directory: ./webapp
        run: npm install

      - name: Build for GitHub Pages
        working-directory: ./webapp
        run: npm run build

      - name: Copy index.html to 404.html (SPA fallback)
        run: cp ./webapp/dist/index.html ./webapp/dist/404.html

      - name: Upload build output
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./webapp/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
